### DISCUSSION TITLE
Decrease ressource usage as much as possible

### DISCUSSION THREAD

**Discussion by DEiscreme** [jlesage/docker-firefox#245] [Q&A] [answered]
Hey,
I use this container to run hundreds of applications. I would love a way to decrease the ressource usage to a bare minimum.
I would love to hear from you! Thanks

I currently use this configuration in docker compose:
```
  name120:
    image: jlesage/firefox:latest
    container_name: name120
    restart: unless-stopped
    ports:
      - "58120:5800"
    network_mode: bridge
    environment:
      - FF_OPEN_URL=https://myurl.com
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - SECURE_CONNECTION_VNC_METHOD=SSL
      - KEEP_APP_RUNNING=1
      - "HTTP_PROXY=http://134.73.65.42:6623"
      - "HTTPS_PROXY=http://134.73.65.42:6623"
      - "http_proxy=http://134.73.65.42:6623"
      - "https_proxy=http://134.73.65.42:6623"
    volumes:
      - '/home/dennise/url/firefox120/:/config'
```
