### DISCUSSION TITLE
Route Audio from the Firefox Container to ALSA on the Docker Host

### DISCUSSION THREAD

**Discussion by mx212** [jlesage/docker-firefox#281] [Q&A] [answered]
Hi, I want to play the audio from the firefox container on the docker host, where the firefox container is running. Currently I only get audio output on the client browser. How can I pass the audio stream to an ALSA loopback device on the docker host?

I use this docker-compose setup:

```
services:
   firefox:
    image: jlesage/firefox
    container_name: firefox
    restart: always
    ports:
      - 5800:5800
    volumes:
      - ./config:/config:rw
    devices:
      - /dev/snd:/dev/snd
    shm_size: 512m
    network_mode: host
    group_add:
      - audio
    environment:
      KEEP_APP_RUNNING: "1"
      APP_NICENESS: "10"
      FF_KIOSK: 0
      WEB_AUDIO: 1 #setting this to 1 plays audio on the client side!
```
From reading other issues here, it seems like this was the default behaviour in the past. The capability to send the audio stream to the client browser is relatively new. When I set `WEB_AUDIO: 0`, soundcloud.com, for example, fails to play audio. With the docker-compose yaml from above, I see this log output: [container.log](https://github.com/user-attachments/files/18550145/container.log). Looks like everything is running correctly.

Any advise would be greatly appreciated.

Also, @jlesage, thank you for this container. I really appreciate the work that has gone into this project.

**Comment by jlesage** [comment]
If you want to play the audio on the host, you need to make sure `WEB_AUDIO` is set to `0` (disabled). From what I understand, you tried that and you fail to ear audio on the host. Did you check permissions on `/dev/snd`, to make sure the configured `USER_ID`/`GROUP_ID` can access it ?

**Comment by mx212** [comment]
Thank you for the hint! I tried different UID and GUI Settings for the container, but none of these worked. I set the GUI explicitly to 995, which is the audio group on my host. Also I startet the container with `privileged: true`. This also had no effect. I noticed that with `WEB_AUDIO` set to `1`, pulseaudio is started. More recent versions of Firefox (very rougly releases from 2021 and newer) require pulseaudio for audio output, but there is apperently a compile option to enable ALSA sound output, as descibed on the [archlinux forum](https://bbs.archlinux.org/viewtopic.php?id=264905).  Direct access to `/dev/snd` sounds to me like an ALSA thing. What I don't understand, is how this worked for people in the past. I am not sure if theire firefox version was old enogh to have ALSA sound output support.
My host system is headless and does not have pulse audio installed. I will try to use `WEB_AUDIO: 1` to enable the pulse audio server in the container and try to reroute the audio to a unix socket. I probably need something like pipewire on the host system to get this to work. This approach is described here: [container sound](https://github.com/mviereck/x11docker/wiki/Container-sound:-ALSA-or-Pulseaudio). currently don't have a lot of time to investigate, but I will report back once I get this working.

**Reply by mx212** [reply, marked as answer]
For future reference, I got this working by installing pipewire on the host system. Pipewire comes with a pulse audio emulator so I think this would also work with pulseaudio. In pipewire, I needed to enable audio via tcp in `/etc/pipewire/pipewire-pulse.conf`, I used:
```
pulse.properties = { 
    server.address = [ 
        "unix:native" 
        "tcp:8889" 
    ] 
}
```
For some reason the stadart port 4713 did not work for me. Then I adjusted the firefox docker.compose.yml to:
```
services:
  firefox:
    image: jlesage/firefox
    container_name: firefox
    restart: always
    ports:
      - 5800:5800
    volumes:
      - ./config:/config:rw
      - ./audiorecorder:/etc/services.d/audiorecorder
    shm_size: 512m
    network_mode: host
    environment:
      KEEP_APP_RUNNING: "1"
      APP_NICENESS: "10"
      FF_KIOSK: 0
      WEB_AUDIO: 1 #setting this to 1 plays audio on the client side!
      PULSE_SERVER: tcp:DockerHostIP:8889
```

here 2 changes are imporant: define the `PULSE_SERVER` environment variable that specifies the address of the pulse audio server on the docker host. And override the `/etc/services.d/audiorecorder` directory in the container with an empty directory to prevent the audiorecorder service from starting, which would send the audio to be played by the client browser. It is not strictly required to disable audiorecorder, but if it is left running, the mute toggle in the control GUI needs to be muted to avoid duplicated audio. Note that I need to use `WEB_AUDIO: 1` to start the pulseaudio server inside of the container. With this setup I get the audio stream from the container in pipewire on the docker host.
