### ISSUE TITLE
Exec format error in Docker compose

### ISSUE THREAD

**Issue by MrMax486** [jlesage/docker-firefox#131]
Hello!
I'm trying to launch the container in docker compose but i get the error:  exec /init: exec format error

this is my configuration:
```
version: '3'
  
services:
  firefox:
    container_name: firefox
    image: jlesage/firefox
    ports:
      - "5800:5800"
    volumes:
      - firefox:/usr/share/firefox_docker:rw
    restart: always

volumes:
  firefox:
```

and this is the result when I try to start the container
```
pi@raspberrypi:~/docker-compose $ docker-compose up firefox
Creating firefox ... done
Attaching to firefox
firefox           | exec /init: exec format error
```

I'm on Raspbian on a RB4

thanks
