### ISSUE TITLE
gluetun issues with 2 docker

### ISSUE THREAD

**Issue by mxwmnn** [jlesage/docker-firefox#159]
I use gluetun to connect docker containers to VPN.

If i add 2 docker instances from you. firefox and jdownloader2 only one is available on the exposed ports.

This is my docker compose which doesnt work only jdownloader2 will be exposed on the port.

```
gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 7800:7800
      - 5800:5800

    volumes:
      - ${APPDATA}gluetun:/gluetun:rw
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=xxxx
      - OPENVPN_PASSWORD=
      - OPENVPN_CIPHERS=aes-256-gcm
      - SERVER_HOSTNAMES=ch-zrh-001,ch-zrh-002,ch-zrh-003,ch-zrh-004,ch-zrh-201,ch-zrh-202
      - FIREWALL_VPN_INPUT_PORTS=55886
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=${TZ}

firefox:
    image: jlesage/firefox
    container_name: ff
    shm_size: 4g
    restart: unless-stopped
    network_mode: "service:gluetun"
    volumes:
      - ${APPDATA}ff:/config:rw
      - ${FF}
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - TZ=${TZ}
      - SECURE_CONNECTION=1
      - VNC_PASSWORD=xxx


  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jd2
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes:
      - ${APPDATA}jd2:/config:rw
      - ${JD}
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - TZ=${TZ}
      - SECURE_CONNECTION=1
      - WEB_LISTENING_PORT=7800

```

How to fix this?

Thanks in advance!
