### ISSUE TITLE
[Bug] Proxy settings aren't applied

### ISSUE THREAD

**Issue by mbrevda** [jlesage/docker-firefox#273]
### Current Behavior

When provisioning proxy settings via env vars, the settings aren't applied until accessing proxy settings via the giu and clicking "OK"

### Expected Behavior

Proxy setting should be applied out of the box

### Steps To Reproduce

docker-compose.yaml
```yaml
services:
  firefox:
    image: jlesage/firefox
    ports:
      - "5800:5800"
    environment:
      FF_PREF_PROXY_HTTP: 'network.proxy.http="foo.bar.baz"'
      FF_PREF_PROXY_HTTP_PORT: 'network.proxy.http_port=8080'
      FF_PREF_PROXY_TYPE: 'network.proxy.type=1'
      FF_PREF_PROXY_SHARE_SETTINGS: 'network.proxy.share_proxy_settings=true'
```

run with `docker compose up`. When running, no paged should be displayed due to the invalid proxy server. Unfortioanlly, browsing works fine (albeit unproxied).

### Environment

I've run in to this issue in multiple environments including locally and cloud hosted (Cloud Run),

### Container creation

see above

### Container log

```text
.
```

**Comment by tboucher204** [comment]
I had the same issue but fixed it by essentially double quoting the string values.  It's as if the variables expect an integer or boolean.  quoting the strings lets the system know they are strings.  I use Ansible for my deployments.  See below, it works for me:


env:
      FF_OPEN_URL: "https://ipinfo.io/what-is-my-ip"
      FF_PREF_DOWNLOAD_DIR: "browser.download.dir='/mnt/downloads/firefox'"
      FF_PREF_PROXY_TYPE: "network.proxy.type=1"
      FF_PREF_HTTP_PROXY: "network.proxy.http='somehost'"
      FF_PREF_HTTP_PROXY_PORT: "network.proxy.http_port=8080"
      FF_PREF_SHARE_PROXY_SETTINGS: "network.proxy.share_proxy_settings=true"

**Comment by mbrevda** [comment]
Isn't that essentially what I posted?
I tried swapping the single and double quotes for the strings, but that didn't help

**Comment by mbrevda** [comment]
FIXED: The issue was that _all_ proxy settings need to be applied. Here is a docker compose that works:

```
services:
  firefox:
    image: jlesage/firefox
    ports:
      - '5800:5800'
    environment:
      FF_PREF_PROXY_BACKUP_SSL: 'network.proxy.backup.ssl=""'
      FF_PREF_PROXY_BACKUP_SSL_PORT: 'network.proxy.backup.ssl_port=0'
      FF_PREF_PROXY_HTTP: 'network.proxy.http="foo.bar.baz"'
      FF_PREF_PROXY_HTTP_PORT: 'network.proxy.http_port=8080'
      FF_PREF_PROXY_SSL: 'network.proxy.ssl="foo.bar.baz"'
      FF_PREF_PROXY_SSL_PORT: 'network.proxy.ssl_port=8080'
      FF_PREF_PROXY_TYPE: 'network.proxy.type=1'
      FF_PREF_PROXY_SHARE_SETTINGS: 'network.proxy.share_proxy_settings=true'
```

Thanks!
